/* 
 * Copyright (c) 2006-2016 RDA Microelectronics, Inc.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


#include "cs_types.h"

#include "at_map.h"
#include "hal_map_engine.h"

// =============================================================================
//  MACROS
// =============================================================================

#define AT_VERSION_STRING	"Hello, I'm AT!"


// =============================================================================
//  GLOBAL VARIABLES
// =============================================================================
#if defined(__AT_IN_DEBUG_HOST__)
extern AT_IN_DBG_HST_ACCESS_T g_atInDbgHstAccess;
#endif /* __AT_IN_DEBUG_HOST__ */

// =============================================================================
// g_atMapVersion
// -----------------------------------------------------------------------------
/// Contains the version of the module.
/// The macro used is generated by the make process.
// =============================================================================
PROTECTED HAL_MAP_VERSION_T g_atMapVersion = 
{
	1,
	0,
	0x20160125,
	AT_VERSION_STRING
};

// =============================================================================
// g_atMapAccess
// -----------------------------------------------------------------------------
/// Contains the addresses of the structures of the module that will be
/// accessible from a remote PC (e.g. through CoolWatcher).
// =============================================================================
PROTECTED AT_MAP_ACCESS_T g_atMapAccess =
{
#if defined(__AT_IN_DEBUG_HOST__)
	&g_atInDbgHstAccess,
#else
	NULL,
#endif /* __AT_IN_DEBUG_HOST__ */
};



// =============================================================================
//  FUNCTIONS
// =============================================================================


// =============================================================================
// at_RegisterYourself
// -----------------------------------------------------------------------------
/// This function registers the module itself to HAL so that the version and
/// the map accessor are filled. Then, the module get version function and the
/// CoolWatcher get version command will work.
// =============================================================================
PUBLIC VOID at_RegisterYourself(VOID)
{
	hal_MapEngineRegisterModule(HAL_MAP_ID_AT, &g_atMapVersion, &g_atMapAccess);
}


