/* 
 * Copyright (c) 2006-2016 RDA Microelectronics, Inc.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
/// @file                                                                     //
/// That file Implements the functions to register the module.
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include "cs_types.h"

#include "hal_map_engine.h"

#include "memd_map.h"



// =============================================================================
//  MACROS
// =============================================================================

#ifdef MEMD_USE_ROMULATOR
#define MEMD_VERSION_STRING "MEMD for Romulator " STRINGIFY_VALUE(ROMU_VER) " emulating " STRINGIFY_VALUE(MEMD_FLSH_MODEL)
#else
#define MEMD_VERSION_STRING "MEMD for " STRINGIFY_VALUE(MEMD_FLSH_MODEL)
#endif
//#include "memdp_version.h"



// =============================================================================
//  GLOBAL VARIABLES
// =============================================================================


// =============================================================================
// g_memdMapVersion
// -----------------------------------------------------------------------------
/// Contains the version of the module.
/// The macro used is generated by the make process.
// =============================================================================
//PROTECTED HAL_MAP_VERSION_T g_memdMapVersion = MEMD_VERSION_STRUCT;



// =============================================================================
// g_memdMapAccess
// -----------------------------------------------------------------------------
/// Contains the addresses of the structures of the module that will be
/// accessible from a remote PC (e.g. through CoolWatcher).
// =============================================================================
PROTECTED MEMD_MAP_ACCESS_T g_memdMapAccess =
{
    // Put your initialization here.
	0x0,
};



// =============================================================================
//  FUNCTIONS
// =============================================================================


// =============================================================================
// memd_RegisterYourself
// -----------------------------------------------------------------------------
/// This function registers the module itself to HAL so that the version and
/// the map accessor are filled. Then, the CSW get version function and the
/// CoolWatcher get version command will work.
// =============================================================================
PUBLIC VOID memd_RegisterYourself(VOID)
{
//    hal_MapEngineRegisterModule(HAL_MAP_ID_MEMD, &g_memdMapVersion, &g_memdMapAccess);
}
