// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "keypad.h"


/////////////////////////////////////////////////////////////////////////////
// CKeypad properties

/////////////////////////////////////////////////////////////////////////////
// CKeypad operations

long CKeypad::GetKeySize()
{
	long result;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CKeypad::AddItem(LPCTSTR lpszName, long nKeyCode, long nLeft, long nTop, long nWidth, long nHeight, LPCTSTR lpszImageUp, LPCTSTR lpszImageDown)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_BSTR VTS_BSTR;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		lpszName, nKeyCode, nLeft, nTop, nWidth, nHeight, lpszImageUp, lpszImageDown);
	return result;
}

void CKeypad::RemoveAll()
{
	InvokeHelper(0x3, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
