/*
* Copyright (c) 2006-2016 RDA Microelectronics, Inc.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CKeypad wrapper class

class CKeypad : public COleDispatchDriver
{
public:
	CKeypad() {}		// Calls COleDispatchDriver default constructor
	CKeypad(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CKeypad(const CKeypad& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetKeySize();
	long AddItem(LPCTSTR lpszName, long nKeyCode, long nLeft, long nTop, long nWidth, long nHeight, LPCTSTR lpszImageUp, LPCTSTR lpszImageDown);
	void RemoveAll();
};
