/*
* Copyright (c) 2006-2016 RDA Microelectronics, Inc.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CScreen wrapper class

class CScreen : public COleDispatchDriver
{
public:
	CScreen() {}		// Calls COleDispatchDriver default constructor
	CScreen(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CScreen(const CScreen& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetLeft();
	void SetLeft(long);
	long GetTop();
	void SetTop(long);
	long GetWidth();
	void SetWidth(long);
	long GetHeight();
	void SetHeight(long);
	long GetColor();
	long GetBKColor();

// Operations
public:
	unsigned long SetPixel(long xPos, long yPos, unsigned long rcColor);
	void UpdateScreen(long* pFrameBuffer, long* pBitmapInfo);
	void UpdateScreenEx(long* pFrameBuffer);
};
