/*
* Copyright (c) 2006-2016 RDA Microelectronics, Inc.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CScreen;
class CKeypad;

/////////////////////////////////////////////////////////////////////////////
// CCoolPhone wrapper class

class CCoolPhone : public CWnd
{
protected:
	DECLARE_DYNCREATE(CCoolPhone)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xab9d831b, 0x277b, 0x4927, { 0x8f, 0x89, 0xc1, 0xcb, 0xbe, 0xb9, 0xe6, 0x11 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	CScreen Screen();
	CScreen SubScreen();
	CKeypad Keypad();
	BOOL LoadPhoneScript(LPCTSTR lpszScript);
	BOOL SetBackgroundImage(LPCTSTR lpszImageFile);
	void LoadSkinProfile(LPCTSTR lpszSkinProfile);
	void ShowSkinSetupDlg();
	void ShowExtendKeyboard(BOOL bShow);
	void ShowExtendKeyboardEx(long xPos, long yPos, BOOL bShow);
    void ShowLeds(long leds_mask);
	void AboutBox();
};
