/* 
 * Copyright (c) 2006-2016 RDA Microelectronics, Inc.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/*********************************************************
 *
 * File Name
 *  at_command_table.c
 * Author
 *  zhangxb
 * Date
 *  2007/11/25
 * Descriptions:
 *
 *  modification:
 *  hameina 2008-4-22 :add AT_PROC_MODE_CS_ENABLE to most of the cmd param
 *
 *********************************************************/

#include "at_common.h"
#include "at_sa.h"


#include "at_cmd_bt.h"


#ifdef WIFI_SUPPORT
#include "at_cmd_wifi.h"
#endif
//#include "at_cmd_bt.h"
#if defined(__AT_GPS__)
#include "at_cmd_special_gps.h"
#endif
#if defined(CFW_TCPIP_SUPPORT)
#include "at_cmd_tcpip.h"
#endif /* CFW_TCPIP_SUPPORT */


#if defined(__AT_MOD_SIM__)
#include "at_cmd_sim.h"
#endif
#if defined(__AT_MOD_SMS__)
#include "at_cmd_sms.h"
#endif
#if defined(__AT_MOD_NW__)
#include "at_cmd_nw.h"
#endif
#if defined(__AT_MOD_GPRS__)
#include "at_cmd_gprs.h"
#endif
#if defined(__AT_MOD_CC__)
#include "at_cmd_cc.h"
#endif
#if defined(__AT_MOD_SS__)
#include "at_cmd_ss.h"
#endif
#if defined(__AT_MOD_ID__)
#include "at_cmd_id.h"
#endif
#if defined(__AT_MOD_SAT__)
#include "at_cmd_sat.h"
#endif
#if defined(__AT_MOD_GC__)
#include "at_cmd_gc.h"
#endif

#if defined(__AT_MOD_MUSIC__)
#include "at_cmd_music.h"
#endif

#if defined(__AT_MOD_FM__)
#include "at_cmd_fm.h"
#endif

#if defined(__AT_MOD_RECORD__)
#include "at_cmd_record.h"
#endif

#if defined(__AT_MOD_COMMON__)
#include "at_cmd_common.h"
#endif

#if (AUDIO_CALIB_VER == 1)
#include "at_cmd_special_emod.h"
#endif

#define FSM_POWER_DOWN_CMD_ENABLE   0x00000001
#define FSM_NORMAL_CMD_ENABLE       0x00000002
#define FSM_CHGR_NORMAL_CMD_ENABLE  0x00000004
#define FSM_CHGR_ONLY_CMD_ENABLE    0x00000008
#define FSM_ALARM_NORMAL_CMD_ENABLE 0x00000010
#define FSM_ALARM_ONLY_CMD_ENABLE   0x00000020
#define FSM_SLEEP_CMD_ENABLE        0x00000040
#define FSM_CFW_OFF_CMD_ENABLE      0x00000080

#define FSM_FULL_STATUS_CMD_ENABLE  ((FSM_NORMAL_CMD_ENABLE)        \
                                    |(FSM_CHGR_NORMAL_CMD_ENABLE)|(FSM_CHGR_ONLY_CMD_ENABLE)        \
                                    |(FSM_ALARM_NORMAL_CMD_ENABLE)|(FSM_ALARM_ONLY_CMD_ENABLE)      \
                                    |(FSM_SLEEP_CMD_ENABLE)|(FSM_CFW_OFF_CMD_ENABLE))

#define FSM_LIMITED1_STATUS_CMD_ENABLE  ((FSM_NORMAL_CMD_ENABLE)|(FSM_CHGR_ONLY_CMD_ENABLE)     \
                                        |(FSM_ALARM_ONLY_CMD_ENABLE))

#define FSM_LIMITED2_STATUS_CMD_ENABLE  ((FSM_NORMAL_CMD_ENABLE)        \
                                        |(FSM_CHGR_NORMAL_CMD_ENABLE)|(FSM_CHGR_ONLY_CMD_ENABLE)        \
                                        |(FSM_ALARM_NORMAL_CMD_ENABLE)|(FSM_ALARM_ONLY_CMD_ENABLE)      \
                                        |(FSM_SLEEP_CMD_ENABLE)|(FSM_CFW_OFF_CMD_ENABLE))

#define FSM_DISABLE_STATUS_CMD_ENABLE   (0x00000000)

#define AT_PROC_MODE_CMD_ENABLE 0x00000001
#define AT_PROC_MODE_OLCMD_ENABLE   0x00000002
#define AT_PROC_MODE_CS_ENABLE  0x00000004
#define AT_PROC_MODE_PS_ENABLE  0x00000008

// [[Hameina[mod] 2008-4-21: can't input at, <cr>in online command state
#define AT_AT_PERM  {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_OLCMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_FA_PERM  {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CR_PERM  {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_OLCMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
// ]]Hameina[mod] 2008-4-21: can't input at, <cr>in online command state

#define AT_REPEAT_PERM  {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_ATD_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_ATH_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_OLCMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
// [[changyg[mod] 2008-4-29 :CS MODE ENABLE
#define AT_ATA_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_OLCMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CLCC_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_VTS_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CHUP_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_VTD_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CHLD_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_DLST_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_VTSEX_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_CMGS_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CMGW_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CPMS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CSCA_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CSMS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CMGD_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CMGF_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_SMGO_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CMGL_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CMGR_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CSDH_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CNMI_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CSMP_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CNMA_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CMSS_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
// #define AT_CACM_PERM   {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CSAS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CRES_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_COPS_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CSQ_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_ECSQ_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_COPN_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CREG_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CPOL_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
// frank add start
#ifdef AT_USER_DBS
#define AT_POSI_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CGSN_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#endif
// frank add start

#define AT_CCWA_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CCFC_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CLIP_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CLIR_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_COLP_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_COLR_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CUSD_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CSSN_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CACM_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_CAOC_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CPUC_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CSVM_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
// add by lijingyu
#define AT_CMUX_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_CFGINIT_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CFGGET_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_BTSET_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_WIFISET_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}

#define AT_CPBS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CPBR_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CPBF_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CPBW_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_WPCS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CNUM_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_STGI_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_STR_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_STA_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_STNR_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_CGMM_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_GMM_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CGMR_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_GMR_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CGMI_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_GMI_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#ifndef AT_USER_DBS
#define AT_CGSN_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#endif
#define AT_GSN_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_ATI_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CIMI_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_CPIN_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CPIN2_PERM   {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CPINC_PERM   {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CLCK_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CPWD_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CRSM_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CAMM_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_SVRADDR_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_DATACLASS_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CONNECT_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_CMER_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CEER_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CMEE_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CFUN_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CSCS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CCLK_PERM    {FSM_LIMITED1_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_ATE_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_ATV_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_ATQ_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_ATZ_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CALA_PERM    {FSM_LIMITED1_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CALD_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_ANDF_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_ATX_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
// #define AT_CALD_PERM   {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}

#define AT_ANDW_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_S0_PERM  {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_S5_PERM  {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_S3_PERM  {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_S4_PERM  {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CDTMF_PERM   {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_IPR_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_ICF_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_IFC_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_MONI_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CCED_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_MONIEND_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_MONP_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_MONPEND_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_SCID_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_SBBI_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_SBBR_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_NBBR_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_SBBW_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_NBBW_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_DPBK_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_DREG_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_DFFS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_DSMS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_PRDU_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_AUST_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_AUEND_PERM   {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_SAIC_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CBC_PERM     {FSM_LIMITED1_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CBCE_PERM    {FSM_LIMITED1_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CBCM_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_SCTM_PERM    {FSM_LIMITED1_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CPAS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CIND_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CLVL_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CMUT_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_VGR_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_VGT_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CRMP_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CAUDIO_PERM  {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_SNFS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_SLCD_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_STCD_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

// ADD by wulc
#define AT_CRSL_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
// CPOF == SMSO  JYK 08/04/08
#define AT_CPOF_PERM    {FSM_LIMITED1_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_CGDCONT_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGQREQ_PERM  {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGQMIN_PERM  {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGATT_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGACT_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGPADDR_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGDATA_PERM  {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGAUTO_PERM  {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGANS_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGCLASS_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGEREP_PERM  {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGREG_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGSMS_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CRC_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGCID_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_TCPIP_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_MUSIC_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_COMMON_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_RECORD_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_FM_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_SYSLPTEST_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#if defined(__AT_CONTROL_BT__)
#define AT_BTINQUIRE_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_BTBIND_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_BTACTIVATE_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_BTSPPENABLE_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#endif
#if defined(__AT_GPS__)
#define AT_GPS_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_GPSSLEEP_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_GPSSEND_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_GPSI2C_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#endif
#if defined(__WIFI_RADIO_BOX__)
#define AT_WRBPLAYURL_PERM      {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_WRBURLLIST       {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_WRBMEDIAPLAY_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_WRBMEDIAPAUSE_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_WRBMEDIARESUM_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_WRBMEDIASTOP_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_WRBMEDIAVOLUME_PERM  {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_WRBSETMODE_PERM           {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_DLNAAVTEST_PERM           {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#endif
#ifdef IP_CAMERA_SUPPORT
#define AT_IPCAMERA_PERM             {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#endif /* IP_CAMERA_SUPPORT */
// #define AT_ATO_PERM  {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_OLCMD_ENABLE}
/*BUG /wulc/2012.02.15/because AT_PROC_MODE_OLCMD_ENABLE cause cmdline parser error*/
#define AT_ATO_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_3PLUS_PERM   {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_OLCMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_ADGF_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
const SA_COMMAND_TABLE_T g_CommandTable[] =
{
    // Command Name            // Command Process Routine
    {(UINT8 *)"AT", SA_DefaultCmdHandler_AT, SA_CMDCLS_SYS, 1, AT_AT_PERM},
    {(UINT8*)"FA", SA_DefaultCmdHandler_Error, SA_CMDCLS_SYS, 1, AT_FA_PERM},
    {(UINT8*)"<CR>", SA_DefaultCmdHandler_CR, SA_CMDCLS_SYS, 1, AT_CR_PERM},
    {(UINT8*)"A/", AT_EX_CmdFunc_RCMD, SA_CMDCLS_SYS, 1, AT_REPEAT_PERM},

#if defined(__AT_MOD_SIM__)
    {(UINT8 *)"+CLCK", AT_SIM_CmdFunc_CLCK, SA_CMDCLS_SIM, 1, AT_CLCK_PERM},
    {(UINT8 *)"+CPWD", AT_SIM_CmdFunc_CPWD, SA_CMDCLS_SIM, 1, AT_CPWD_PERM},
    {(UINT8 *)"+CPIN", AT_SIM_CmdFunc_CPIN, SA_CMDCLS_SIM, 1, AT_CPIN_PERM},
    {(UINT8 *)"+CRSM", AT_SIM_CmdFunc_CRSM, SA_CMDCLS_SIM, 1, AT_CRSM_PERM},
    {(UINT8 *)"+CAMM", AT_SIM_CmdFunc_CAMM, SA_CMDCLS_SIM, 1, AT_CAMM_PERM},
//    {(UINT8 *)"^SIMIF", AT_SIM_CmdFunc_SIMIF, SA_CMDCLS_SIM, 1, AT_SIMIF_PERM},

    {(UINT8 *)"+CPIN2", AT_SIM_CmdFunc_CPIN2, SA_CMDCLS_SIM, 1, AT_CPIN2_PERM},
    {(UINT8 *)"^CPINC", AT_SIM_CmdFunc_CPINC, SA_CMDCLS_SIM, 1, AT_CPINC_PERM},
    {(UINT8 *)"+CRSML", AT_SIM_CmdFunc_CRSML, SA_CMDCLS_SIM, 1, AT_CRSM_PERM},
    {(UINT8 *)"+CRESET", AT_SIM_CmdFunc_CRESET, SA_CMDCLS_SIM, 1, AT_CAMM_PERM},
    {(UINT8 *)"+CSST", AT_SIM_CmdFunc_CSST, SA_CMDCLS_SIM, 1, AT_CAMM_PERM},
#endif

    /*Commands for GPRS*/
#ifdef __AT_MOD_GPRS__
    {(UINT8 *)"+CGDCONT", AT_GPRS_CmdFunc_CGDCONT, SA_CMDCLS_GPRS, 1, AT_CGDCONT_PERM},
//    {(UINT8 *)"+CGDSCONT", AT_GPRS_CmdFunc_CGDSCONT, SA_CMDCLS_GPRS, 1, AT_CGDSCONT_PERM},
    {(UINT8 *)"+CGQREQ", AT_GPRS_CmdFunc_CGQREQ, SA_CMDCLS_GPRS, 1, AT_CGQREQ_PERM},
    {(UINT8 *)"+CGQMIN", AT_GPRS_CmdFunc_CGQMIN, SA_CMDCLS_GPRS, 1, AT_CGQMIN_PERM},
    {(UINT8 *)"+CGATT", AT_GPRS_CmdFunc_CGATT, SA_CMDCLS_GPRS, 1, AT_CGATT_PERM},
    {(UINT8 *)"+CGACT", AT_GPRS_CmdFunc_CGACT, SA_CMDCLS_GPRS, 1, AT_CGACT_PERM},
    {(UINT8 *)"+CGDATA", AT_GPRS_CmdFunc_CGDATA, SA_CMDCLS_GPRS, 1, AT_CGDATA_PERM},
    {(UINT8 *)"+CGPADDR", AT_GPRS_CmdFunc_CGPADDR, SA_CMDCLS_GPRS, 1, AT_CGPADDR_PERM},
    {(UINT8 *)"+CGAUTO", AT_GPRS_CmdFunc_CGAUTO, SA_CMDCLS_GPRS, 1, AT_CGAUTO_PERM},
    {(UINT8 *)"+CGANS", AT_GPRS_CmdFunc_CGANS, SA_CMDCLS_GPRS, 1, AT_CGANS_PERM},
    {(UINT8 *)"+CGCLASS", AT_GPRS_CmdFunc_CGCLASS, SA_CMDCLS_GPRS, 1, AT_CGCLASS_PERM},
    {(UINT8 *)"+CGEREP", AT_GPRS_CmdFunc_CGEREP, SA_CMDCLS_GPRS, 1, AT_CGEREP_PERM},
    {(UINT8 *)"+CGREG", AT_GPRS_CmdFunc_CGREG, SA_CMDCLS_GPRS, 1, AT_CGREG_PERM},
    {(UINT8 *)"+CGSMS", AT_GPRS_CmdFunc_CGSMS, SA_CMDCLS_GPRS, 1, AT_CGSMS_PERM},
//    {(UINT8 *)"+CGPDNSADDR", AT_GPRS_CmdFunc_CGPDNSADDR, SA_CMDCLS_GPRS, 1, AT_CGSMS_PERM},
#ifdef __MULTI_RAT__
//    {(UINT8 *)"+CGEQREQ", AT_GPRS_CmdFunc_CGEQREQ, SA_CMDCLS_GPRS, 1, AT_CGSMS_PERM},
//    {(UINT8 *)"+CGEQMIN", AT_GPRS_CmdFunc_CGEQMIN, SA_CMDCLS_GPRS, 1, AT_CGSMS_PERM},
#endif
    {(UINT8 *)"+CRC", AT_GPRS_CmdFunc_CRC, SA_CMDCLS_GPRS, 1, AT_CRC_PERM},
    {(UINT8 *)"+CGCID", AT_GPRS_CmdFunc_CGCID, SA_CMDCLS_GPRS, 1, AT_CGCID_PERM},
    {(UINT8 *)"+CGSEND", AT_GPRS_CmdFunc_CGSEND, SA_CMDCLS_GPRS, 1, AT_CGCID_PERM},
#endif

    //3GPP TS 27.005 V3.2.0
#if defined(__AT_MOD_SMS__)
    /*For SMS Commands*/
    {(UINT8 *)"+CSMS", AT_SMS_CmdFunc_CSMS, SA_CMDCLS_SMS, 1, AT_CSMS_PERM},
    {(UINT8 *)"+CPMS", AT_SMS_CmdFunc_CPMS, SA_CMDCLS_SMS, 1, AT_CPMS_PERM},
    {(UINT8 *)"+CMGF", AT_SMS_CmdFunc_CMGF, SA_CMDCLS_SMS, 1, AT_CMGF_PERM},
    {(UINT8 *)"+CSCA", AT_SMS_CmdFunc_CSCA, SA_CMDCLS_SMS, 1, AT_CSCA_PERM},
    {(UINT8 *)"+CSMP", AT_SMS_CmdFunc_CSMP, SA_CMDCLS_SMS, 1, AT_CSMP_PERM},
    {(UINT8 *)"+CSDH", AT_SMS_CmdFunc_CSDH, SA_CMDCLS_SMS, 1, AT_CSDH_PERM},

    {(UINT8 *)"+CSAS", AT_SMS_CmdFunc_CSAS, SA_CMDCLS_SMS, 1, AT_CSAS_PERM},
    {(UINT8 *)"+CRES", AT_SMS_CmdFunc_CRES, SA_CMDCLS_SMS, 1, AT_CRES_PERM},
    {(UINT8 *)"+CNMI", AT_SMS_CmdFunc_CNMI, SA_CMDCLS_SMS, 1, AT_CNMI_PERM},
    {(UINT8 *)"+CMGL", AT_SMS_CmdFunc_CMGL, SA_CMDCLS_SMS, 1, AT_CMGL_PERM},
    {(UINT8 *)"+CMGR", AT_SMS_CmdFunc_CMGR, SA_CMDCLS_SMS, 1, AT_CMGR_PERM},
    {(UINT8 *)"+CNMA", AT_SMS_CmdFunc_CNMA, SA_CMDCLS_SMS, 1, AT_CNMA_PERM},
    {(UINT8 *)"+CMGS", AT_SMS_CmdFunc_CMGS, SA_CMDCLS_SMS, 1, AT_CMGS_PERM},
    {(UINT8 *)"+CMSS", AT_SMS_CmdFunc_CMSS, SA_CMDCLS_SMS, 1, AT_CMSS_PERM},
    {(UINT8 *)"+CMGW", AT_SMS_CmdFunc_CMGW, SA_CMDCLS_SMS, 1, AT_CMGW_PERM},
    {(UINT8 *)"+CMGD", AT_SMS_CmdFunc_CMGD, SA_CMDCLS_SMS, 1, AT_CMGD_PERM},
#ifdef CB_SUPPORT
//    {(UINT8 *)"+CSCB", AT_SMS_CmdFunc_CSCB, SA_CMDCLS_SMS, 1, AT_CSCB_PERM},
#endif
#endif /*__AT_MOD_SMS__*/

#if defined(__AT_MOD_NW__)
    /*Network service related commands*/
    {(UINT8 *)"+CREG", AT_NW_CmdFunc_CREG, SA_CMDCLS_NW, 1, AT_CREG_PERM},
    {(UINT8 *)"+COPS", AT_NW_CmdFunc_COPS, SA_CMDCLS_NW, 1, AT_COPS_PERM},
    {(UINT8 *)"+CPOL", AT_NW_CmdFunc_CPOL, SA_CMDCLS_NW, 1, AT_CPOL_PERM},
    {(UINT8 *)"+COPN", AT_NW_CmdFunc_COPN, SA_CMDCLS_NW, 1, AT_COPN_PERM},
//    {(UINT8 *)"+SETBND", AT_NW_CmdFunc_SETBND, SA_CMDCLS_NW, 1, AT_COPS_PERM},
    {(UINT8 *)"+CSQ", AT_NW_CmdFunc_CSQ, SA_CMDCLS_NW, 1, AT_CSQ_PERM},
#ifdef __MULTI_RAT__
//    {(UINT8 *)"+SNWR", AT_NW_CmdFunc_SNWR, SA_CMDCLS_NW, 1, AT_CSQ_PERM},
#endif
    {(UINT8 *)"+ECSQ", AT_NW_CmdFunc_ECSQ, SA_CMDCLS_NW, 1, AT_ECSQ_PERM},
    {(UINT8 *)"+CCED", AT_NW_CmdFunc_CCED, SA_CMDCLS_NW, 1, AT_CCED_PERM},
    {(UINT8 *)"^CCED", AT_NW_CmdFunc_CCED, SA_CMDCLS_NW, 1, AT_CCED_PERM},
    {(UINT8 *)"+CBINDARFCN", AT_NW_CmdFunc_CBindArfcn, SA_CMDCLS_NW, 1, AT_CCED_PERM},
//    {(UINT8 *)"+LOCKBCCH", AT_NW_CmdFunc_LOCKBCCH, SA_CMDCLS_NW, 1, AT_CCED_PERM},
#endif /*__AT_MOD_NW__*/

#if defined(__AT_MOD_CC__)
    {(UINT8 *)"D", AT_CC_CmdFunc_D, SA_CMDCLS_CC, 1, AT_ATD_PERM},
    {(UINT8 *)"+++", AT_CC_CmdFunc_3PLUS, SA_CMDCLS_SYS, 1, AT_3PLUS_PERM},
    {(UINT8 *)"O", AT_CC_CmdFunc_O, SA_CMDCLS_CC, 1, AT_ATO_PERM},
    {(UINT8 *)"H", AT_CC_CmdFunc_H, SA_CMDCLS_CC, 1, AT_ATH_PERM},
    {(UINT8 *)"A", AT_CC_CmdFunc_A, SA_CMDCLS_CC, 1, AT_ATA_PERM},
    {(UINT8 *)"+CHUP", AT_CC_CmdFunc_CHUP, SA_CMDCLS_CC, 1, AT_CHUP_PERM},
    {(UINT8 *)"+CHLD", AT_CC_CmdFunc_CHLD, SA_CMDCLS_CC, 1, AT_CHLD_PERM},
    {(UINT8 *)"+CLCC", AT_CC_CmdFunc_CLCC, SA_CMDCLS_CC, 1, AT_CLCC_PERM},
    {(UINT8 *)"+VTS", AT_CC_CmdFunc_VTS, SA_CMDCLS_CC, 1, AT_VTS_PERM},
    {(UINT8 *)"+VTD", AT_CC_CmdFunc_VTD, SA_CMDCLS_CC, 1, AT_VTD_PERM},
    {(UINT8 *)"+CRC", AT_CC_CmdFunc_CRC, SA_CMDCLS_CC, 1, AT_CRC_PERM},
    {(UINT8 *)"+VTSEX", AT_CC_CmdFunc_VTSEX, SA_CMDCLS_CC, 1, AT_VTSEX_PERM},
    {(UINT8 *)"+DLST", AT_CC_CmdFunc_DLST, SA_CMDCLS_CC, 1, AT_DLST_PERM},
#endif /*__AT_MOD_CC__*/

#if defined(__AT_MOD_SS__)
    {(UINT8 *)"+CLIP", AT_SS_CmdFunc_CLIP, SA_CMDCLS_SS, 1, AT_CLIP_PERM},
    {(UINT8 *)"+CLIR", AT_SS_CmdFunc_CLIR, SA_CMDCLS_SS, 1, AT_CLIR_PERM},
    {(UINT8 *)"+COLP", AT_SS_CmdFunc_COLP, SA_CMDCLS_SS, 1, AT_COLP_PERM},
    {(UINT8 *)"+CCFC", AT_SS_CmdFunc_CCFC, SA_CMDCLS_SS, 1, AT_CCFC_PERM},
    {(UINT8 *)"+CCWA", AT_SS_CmdFunc_CCWA, SA_CMDCLS_SS, 1, AT_CCWA_PERM},
    {(UINT8 *)"+CUSD", AT_SS_CmdFunc_CUSD, SA_CMDCLS_SS, 1, AT_CUSD_PERM},
    {(UINT8 *)"+CAOC", AT_SS_CmdFunc_CAOC, SA_CMDCLS_SS, 1, AT_CAOC_PERM},
    {(UINT8 *)"+CSSN", AT_SS_CmdFunc_CSSN, SA_CMDCLS_SS, 1, AT_CSSN_PERM},
    {(UINT8 *)"+CACM", AT_SS_CmdFunc_CACM, SA_CMDCLS_SS, 1, AT_CACM_PERM},
    {(UINT8 *)"+CPUC", AT_SS_CmdFunc_CPUC, SA_CMDCLS_SS, 1, AT_CPUC_PERM},
    {(UINT8 *)"+SAVECLIR", AT_SS_CmdFunc_SAVECLIR, SA_CMDCLS_SS, 1, AT_CLIR_PERM},
    {(UINT8 *)"+COLR", AT_SS_CmdFunc_COLR, SA_CMDCLS_SS, 1, AT_COLR_PERM},
#endif /*__AT_MOD_SS__*/

#if defined(__AT_MOD_GC__)
    {(UINT8 *)"Z", AT_GC_CmdFunc_Z, SA_CMDCLS_GC, 1, AT_ATZ_PERM},
    {(UINT8 *)"&F", AT_GC_CmdFunc_AndF, SA_CMDCLS_GC, 1, AT_ANDF_PERM},
    {(UINT8 *)"E", AT_GC_CmdFunc_E, SA_CMDCLS_GC, 1, AT_ATE_PERM},
    {(UINT8 *)"V", AT_GC_CmdFunc_V, SA_CMDCLS_GC, 1, AT_ATV_PERM},
    {(UINT8 *)"Q", AT_GC_CmdFunc_Q, SA_CMDCLS_GC, 1, AT_ATQ_PERM},
    {(UINT8 *)"&W", AT_GC_CmdFunc_AndW, SA_CMDCLS_GC, 1, AT_ANDW_PERM},
    {(UINT8 *)"S0", AT_GC_CmdFunc_S0, SA_CMDCLS_GC, 1, AT_S0_PERM},
    {(UINT8 *)"S5", AT_GC_CmdFunc_S5, SA_CMDCLS_GC, 1, AT_S5_PERM},
    {(UINT8 *)"S3", AT_GC_CmdFunc_S3, SA_CMDCLS_GC, 1, AT_S3_PERM},
    {(UINT8 *)"S4", AT_GC_CmdFunc_S4, SA_CMDCLS_GC, 1, AT_S4_PERM},
    {(UINT8 *)"X", AT_GC_CmdFunc_X, SA_CMDCLS_GC, 1, AT_ATX_PERM},
    {(UINT8 *)"+IPR", AT_GC_CmdFunc_IPR, SA_CMDCLS_GC, 1, AT_IPR_PERM},
    {(UINT8 *)"+ICF", AT_GC_CmdFunc_ICF, SA_CMDCLS_GC, 1, AT_ICF_PERM},
    {(UINT8 *)"+IFC", AT_GC_CmdFunc_IFC, SA_CMDCLS_GC, 1, AT_IFC_PERM},
//  {(UINT8 *)"+OTP", AT_GC_CmdFunc_OTP, SA_CMDCLS_GC, 1, AT_IFC_PERM},
    {(UINT8 *)"+CSCS", AT_GC_CmdFunc_CSCS, SA_CMDCLS_GC, 1, AT_CSCS_PERM},
    {(UINT8 *)"+CPAS", AT_GC_CmdFunc_CPAS, SA_CMDCLS_EX, 1, AT_CPAS_PERM},
    {(UINT8 *)"+CFUN", AT_GC_CmdFunc_CFUN, SA_CMDCLS_GC, 1, AT_AT_PERM},
    {(UINT8 *)"+CIND", AT_GC_CmdFunc_CIND, SA_CMDCLS_EX, 1, AT_CIND_PERM},
    {(UINT8 *)"+CMER", AT_GC_CmdFunc_CMER, SA_CMDCLS_GC, 1, AT_CMER_PERM},
    {(UINT8 *)"+CCLK", AT_GC_CmdFunc_CCLK, SA_CMDCLS_GC, 1, AT_CCLK_PERM},
    {(UINT8 *)"+CALA", AT_GC_CmdFunc_CALA, SA_CMDCLS_GC, 1, AT_CALA_PERM},
    {(UINT8 *)"+CALD", AT_GC_CmdFunc_CALD, SA_CMDCLS_GC, 1, AT_CALD_PERM},
    {(UINT8 *)"+CMEE", AT_GC_CmdFunc_CMEE, SA_CMDCLS_GC, 1, AT_CMEE_PERM},
    {(UINT8 *)"+EGMR", AT_GC_CmdFunc_EGMR, SA_CMDCLS_SYS, 1, AT_AT_PERM},
    {(UINT8 *)"+CEER", AT_GC_CmdFunc_CEER, SA_CMDCLS_GC, 1, AT_CEER_PERM},
    {(UINT8 *)"+ACLB", AT_GC_CmdFunc_ACLB, SA_CMDCLS_GC, 1, AT_ATX_PERM},
    {(UINT8 *)"+CDTMF", AT_GC_CmdFunc_CDTMF, SA_CMDCLS_GC, 1, AT_CDTMF_PERM},
    {(UINT8 *)"+CPOF", AT_GC_CmdFunc_CPOF, SA_CMDCLS_EX, 1, AT_CPOF_PERM},
#endif /*__AT_MOD_GC__*/

#if defined(__AT_MOD_ID__)
    {(UINT8 *)"I", AT_ID_CmdFunc_I, SA_CMDCLS_ID, 1, AT_ATI_PERM},
    {(UINT8 *)"+GMI", AT_ID_CmdFunc_GMI, SA_CMDCLS_ID, 1, AT_GMI_PERM},
    {(UINT8 *)"+GMM", AT_ID_CmdFunc_GMM, SA_CMDCLS_ID, 1, AT_GMM_PERM},
    {(UINT8 *)"+GMR", AT_ID_CmdFunc_GMR, SA_CMDCLS_ID, 1, AT_GMR_PERM},
    {(UINT8 *)"+GSN", AT_ID_CmdFunc_GSN, SA_CMDCLS_ID, 1, AT_GSN_PERM},
    {(UINT8 *)"+CGMI", AT_ID_CmdFunc_CGMI, SA_CMDCLS_ID, 1, AT_CGMI_PERM},
    {(UINT8 *)"+CGMM", AT_ID_CmdFunc_CGMM, SA_CMDCLS_ID, 1, AT_CGMM_PERM},
    {(UINT8 *)"+CGMR", AT_ID_CmdFunc_CGMR, SA_CMDCLS_ID, 1, AT_CGMR_PERM},
    {(UINT8 *)"+CGSN", AT_ID_CmdFunc_CGSN, SA_CMDCLS_ID, 1, AT_CGSN_PERM},
    {(UINT8 *)"+CIMI", AT_ID_CmdFunc_CIMI, SA_CMDCLS_ID, 1, AT_CIMI_PERM},
    {(UINT8 *)"+CGBV", AT_ID_CmdFunc_CGBV, SA_CMDCLS_ID, 1, AT_CIMI_PERM},
#endif /*__AT_MOD_ID__*/

#if defined(__AT_MOD_CFG__)
#endif /*__AT_MOD_CFG__*/

#if defined(__AT_MOD_DFMS__)
#endif /*__AT_MOD_DFMS__*/

#if defined(__AT_MOD_SAT__)
    {(UINT8 *)"^STGI", AT_SAT_CmdFunc_STGI, SA_CMDCLS_SAT, 1, AT_STGI_PERM},
    {(UINT8 *)"^STR", AT_SAT_CmdFunc_STR, SA_CMDCLS_SAT, 1, AT_STR_PERM},
    {(UINT8 *)"^STA", AT_SAT_CmdFunc_STA, SA_CMDCLS_SAT, 1, AT_STA_PERM},
    {(UINT8 *)"^STNR", AT_SAT_CmdFunc_STNR, SA_CMDCLS_SAT, 1, AT_STNR_PERM},
    {(UINT8 *)"^STRC", AT_SAT_CmdFunc_STRC, SA_CMDCLS_SAT, 1, AT_STNR_PERM},
#endif /*__AT_MOD_SAT__*/

#if defined(__AT_MOD_WIFI__)
    {(UINT8*)"+WPOWER", AT_WIFI_CmdFunc_WPOWER, SA_CMDCLS_EX, 1, AT_WIFISET_PERM},
    {(UINT8*)"+WSCAN", AT_WIFI_CmdFunc_WSCAN, SA_CMDCLS_EX, 1, AT_WIFISET_PERM},
    {(UINT8*)"+WJOIN", AT_WIFI_CmdFunc_WJOIN, SA_CMDCLS_EX, 1, AT_WIFISET_PERM},
    {(UINT8*)"+WADDR", AT_WIFI_CmdFunc_WADDR, SA_CMDCLS_EX, 1, AT_WIFISET_PERM},
    {(UINT8*)"+WACON", AT_WIFI_CmdFunc_WACON, SA_CMDCLS_EX, 1, AT_WIFISET_PERM},
    {(UINT8*)"+WRESET", AT_WIFI_CmdFunc_WRESET, SA_CMDCLS_EX, 1, AT_WIFISET_PERM},
#if 0//!defined(WIN32)
    {(UINT8*)"+WIOPEN", AT_WIFI_CmdFunc_iOpen, SA_CMDCLS_EX, 1, AT_WIFISET_PERM},
    {(UINT8*)"+IOPEN", AT_WIFI_CmdFunc_iTOpen, SA_CMDCLS_EX, 1, AT_WIFISET_PERM},
    {(UINT8*)"+ICLOSE", AT_WIFI_CmdFunc_iTClose, SA_CMDCLS_EX, 1, AT_WIFISET_PERM},
    {(UINT8*)"+ISET", AT_WIFI_CmdFunc_iTSet, SA_CMDCLS_EX, 1, AT_WIFISET_PERM},
    {(UINT8*)"+ISETREG", AT_WIFI_CmdFunc_iTSetReg, SA_CMDCLS_EX, 1, AT_WIFISET_PERM},
#endif
#endif
#ifdef __WIFI_TEST_INDEX__
  {(UINT8*)"+SETCH", AT_WIFI_TM_CmdFunc_Setch, SA_CMDCLS_EX, 1, AT_WIFISET_PERM},
  {(UINT8*)"+SETR", AT_WIFI_TM_CmdFunc_Setr, SA_CMDCLS_EX, 1, AT_WIFISET_PERM},
  {(UINT8*)"+WRX", AT_WIFI_TM_CmdFunc_Rx, SA_CMDCLS_EX, 1, AT_WIFISET_PERM},
  {(UINT8*)"+WTX", AT_WIFI_TM_CmdFunc_Tx, SA_CMDCLS_EX, 1, AT_WIFISET_PERM},
  {(UINT8*)"+WTMPU", AT_WIFI_TM_CmdFunc_Powerup, SA_CMDCLS_EX, 1, AT_WIFISET_PERM},
  {(UINT8*)"+WTMPD", AT_WIFI_TM_CmdFunc_Powerdown, SA_CMDCLS_EX, 1, AT_WIFISET_PERM},
  {(UINT8*)"+UTTXLEN", AT_WIFI_TM_CmdFunc_Uttxlen, SA_CMDCLS_EX, 1, AT_WIFISET_PERM},
  {(UINT8*)"+RFREGW", AT_WIFI_TM_CmdFunc_Rfregw, SA_CMDCLS_EX, 1, AT_WIFISET_PERM},

#endif

#if defined(__WIFI_RADIO_BOX__)
    {(UINT8*)"+WRBPLAYURL", AT_EMOD_CmdFunc_WRBPLAYURL, SA_CMDCLS_EX, 1, AT_WRBPLAYURL_PERM},
    {(UINT8*)"+WRBURLLIST", AT_EMOD_CmdFunc_WRBURLLIST, SA_CMDCLS_EX, 1, AT_WRBURLLIST},
    {(UINT8*)"+WRBMEDIAPLAY", AT_EMOD_CmdFunc_WRBMEDIAPLAY, SA_CMDCLS_EX, 1, AT_WRBMEDIAPLAY_PERM},
    {(UINT8*)"+WRBMEDIAPAUSE", AT_EMOD_CmdFunc_WRBMEDIAPAUSE, SA_CMDCLS_EX, 1, AT_WRBMEDIAPAUSE_PERM},
    {(UINT8*)"+WRBMEDIARESUME", AT_EMOD_CmdFunc_WRBMEDIARESUME, SA_CMDCLS_EX, 1, AT_WRBMEDIARESUM_PERM},
    {(UINT8*)"+WRBMEDIASTOP", AT_EMOD_CmdFunc_WRBMEDIASTOP, SA_CMDCLS_EX, 1, AT_WRBMEDIASTOP_PERM},
    {(UINT8*)"+WRBMEDIAVOLUME", AT_EMOD_CmdFunc_WRBMEDIAVOLUME, SA_CMDCLS_EX, 1, AT_WRBMEDIAVOLUME_PERM},
//  {(UINT8*)"+WRBSETMODE", AT_EMOD_CmdFunc_WRBSETMODE, SA_CMDCLS_EX, 1, AT_WRBSETMODE_PERM},
//  {(UINT8*)"+DLNAAVTEST", AT_EMOD_CmdFunc_DLNAAVTEST, SA_CMDCLS_EX, 1, AT_DLNAAVTEST_PERM},
#endif

#if defined(__AT_MOD_BT__)
//#ifdef WIN32
    {(UINT8*)"+BTOPEN", AT_EMOD_CmdFunc_BTOPEN, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTCLOSE", AT_EMOD_CmdFunc_BTCLOSE, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTVISIBLE", AT_EMOD_CmdFunc_BTVISIBLE, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTINVISIBLE", AT_EMOD_CmdFunc_BTINVISIBLE, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTSETNAME", AT_EMOD_CmdFunc_BTSETNAME, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTSWITCH", AT_EMOD_CmdFunc_BTSWITCH, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTINQUIRY", AT_EMOD_CmdFunc_BTINQUIRY, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTINQUIRYCANCEL", AT_EMOD_CmdFunc_BTINQUIRECANCEL, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTGETRSSI", AT_EMOD_CmdFunc_BTGETRSSI, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTSETADDR", AT_EMOD_CmdFunc_BTSETADDR, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTSETLNAME", AT_EMOD_CmdFunc_BTSETLNAME, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTGETSTATUS", AT_EMOD_CmdFunc_BTGETSTATUS, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTGETA2DPSTATUS", AT_EMOD_CmdFunc_BTGETA2DPSTATUS, SA_CMDCLS_EX, 1, AT_AT_PERM},

#if APP_SUPPORT_LE == 1
    {(UINT8*)"+LESBAS", AT_EMOD_CmdFunc_LE_START_BAS, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+LESIAS", AT_EMOD_CmdFunc_LE_START_IAS, SA_CMDCLS_EX, 1, AT_AT_PERM},
#ifdef CODEC_SUPPORT
    {(UINT8*)"+LESWIFISCS", AT_EMOD_CmdFunc_LE_START_WIFISCS, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+LEGETCONFIGSTATE", AT_EMOD_CmdFunc_LE_WIFISCS_GETCONFIGSTATE, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+LEGETCONFIGINFO", AT_EMOD_CmdFunc_LE_WIFISCS_GETAPINFO, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+LESETINDICATION", AT_EMOD_CmdFunc_LE_WIFISCS_SETSTATE, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+LESETFEATURE", AT_EMOD_CmdFunc_LE_WIFISCS_SETFEATURE, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+LEGETINDSTATE", AT_EMOD_CmdFunc_LE_WIFISCS_GETINDSTATE, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+LECLEARCONFIGINFO", AT_EMOD_CmdFunc_LE_WIFISCS_CLEARAPINFO, SA_CMDCLS_EX, 1, AT_AT_PERM},
#endif
#endif

#if APP_SUPPORT_AVRCP == 1
    {(UINT8*)"+BTCONAVRCP", AT_EMOD_CmdFunc_BTAVRCPCONNECT, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTDISCAVRCP", AT_EMOD_CmdFunc_BTAVRCPDISCONNECT, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTPLAY", AT_EMOD_CmdFunc_BTPLAY, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTPAUSE", AT_EMOD_CmdFunc_BTPAUSE, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTFORWARD", AT_EMOD_CmdFunc_BTFORWARD, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTBACKWARD", AT_EMOD_CmdFunc_BTBACKWARD, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTGETTRACKINFO", AT_EMOD_CmdFunc_BTGETTRACKINFO, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTVOLUP", AT_EMOD_CmdFunc_BTVOLUP, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTVOLDOWN", AT_EMOD_CmdFunc_BTVOLDOWN, SA_CMDCLS_EX, 1, AT_AT_PERM},
#endif
#if APP_SUPPORT_HFP == 1
    {(UINT8*)"+BTCONHFP", AT_EMOD_CmdFunc_HFPCONNECT, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTDISCHFP", AT_EMOD_CmdFunc_HFPDISCONNECT, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTACCEPTCALL", AT_EMOD_CmdFunc_HFPACCEPTCALL, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTREJECTCALL", AT_EMOD_CmdFunc_HFPREJECTCALL, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTTERMINALCALL", AT_EMOD_CmdFunc_HFPTERMINALCALL, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTCALL", AT_EMOD_CmdFunc_HFPCALL, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTSENDAT", AT_EMOD_CmdFunc_HFPSENDAT, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTATGETPB", AT_EMOD_CmdFunc_HFPGETPB, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTCONSCO", AT_EMOD_CmdFunc_HFPCONSCO, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTDISCSCO", AT_EMOD_CmdFunc_HFPDISCSCO, SA_CMDCLS_EX, 1, AT_AT_PERM},
#endif
#if APP_SUPPORT_TEST_BOX == 1
    {(UINT8*)"+BTCDN", AT_EMOD_CmdFunc_HFPCDN, SA_CMDCLS_EX, 1, AT_AT_PERM},
#endif
#if APP_SUPPORT_PBAP==1
    {(UINT8*)"+BTGETPB", AT_EMOD_CmdFunc_GETPB, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTGETCR", AT_EMOD_CmdFunc_GETCR, SA_CMDCLS_EX, 1, AT_AT_PERM},
#endif
#if APP_SUPPORT_FCC==1
    {(UINT8*)"+BTFCCTEST", AT_EMOD_CmdFunc_FCC, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTFCCSTOP", AT_EMOD_CmdFunc_FCCSTOP, SA_CMDCLS_EX, 1, AT_AT_PERM},
#endif
#if APP_SUPPORT_DUT==1
    {(UINT8*)"+BTDUTTEST", AT_EMOD_CmdFunc_BTDUTTEST, SA_CMDCLS_EX, 1, AT_AT_PERM},
#endif
#if APP_SUPPORT_VCO==1
    {(UINT8*)"+BTVCOTEST", AT_EMOD_CmdFunc_BTVCOTEST, SA_CMDCLS_EX, 1, AT_AT_PERM},
#endif

#if APP_SUPPORT_MAP==1
    {(UINT8*)"+BTGETMAP", AT_EMOD_CmdFunc_GETMAP, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTSETMNS", AT_EMOD_CmdFunc_SETMNS, SA_CMDCLS_EX, 1, AT_AT_PERM},
#endif

#if APP_SUPPORT_A2DP == 1
    {(UINT8*)"+BTCONA2DP", AT_EMOD_CmdFunc_A2DPCONNECT, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTDISCA2DP", AT_EMOD_CmdFunc_A2DPDISCONNECT, SA_CMDCLS_EX, 1, AT_AT_PERM},
#endif
#if APP_SUPPORT_HID == 1
    {(UINT8*)"+BTCONHID", AT_EMOD_CmdFunc_CONHID, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTHIDTP", AT_EMOD_CmdFunc_HIDTP, SA_CMDCLS_EX, 1, AT_AT_PERM},
#endif
#if APP_SUPPORT_SPP == 1
    {(UINT8*)"+BTCONSPP", AT_EMOD_CmdFunc_BTSPPCONNECT, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTDISCSPP", AT_EMOD_CmdFunc_BTSPPDISCONNECT, SA_CMDCLS_EX, 1, AT_AT_PERM},
    {(UINT8*)"+BTSENDSPPDATA", AT_EMOD_CmdFunc_BTSPPSENDDATA, SA_CMDCLS_EX, 1, AT_AT_PERM},
#endif
//#endif
#endif

#ifdef IP_CAMERA_SUPPORT
    {(UINT8*)"+IPCAMOPEN", AT_IPCAM_CmdFunc_OPEN, SA_CMDCLS_EX, 1, AT_IPCAMERA_PERM},
    {(UINT8*)"+IPCAMCLOSE", AT_IPCAM_CmdFunc_CLOSE, SA_CMDCLS_EX, 1, AT_IPCAMERA_PERM},
#endif /* IP_CAMERA_SUPPORT */
#if defined(__ZBAR_SUPPORT__)
    {(UINT8*)"+IPCAMQRDEC", AT_WIFI_CmdFunc_QRDEC, SA_CMDCLS_EX, 1, AT_IPCAMERA_PERM},
#endif /* __ZBAR_SUPPORT__ */

#if defined(__AT_MOD_TCPIP__)
  {(UINT8*)"+IPCONFIG", AT_TCPIP_CmdFunc_Ipconfig, SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
  {(UINT8*)"+SOPEN", AT_TCPIP_CmdFunc_ConnectTo, SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
  {(UINT8*)"+SCLOSE", AT_TCPIP_CmdFunc_DisConnect, SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
  {(UINT8*)"+LISTEN", AT_TCPIP_CmdFunc_Listen, SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
  {(UINT8*)"+SREAD", AT_TCPIP_CmdFunc_SRead, SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
  {(UINT8*)"+SWRITE", AT_TCPIP_CmdFunc_SWrite, SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
  {(UINT8*)"+STEST", AT_TCPIP_CmdFunc_SocTest, SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
#endif /* CFW_TCPIP_SUPPORT */

#if defined(__AT_MOD_MUSIC__)
  {(UINT8*)"+MPLAY", AT_MUSIC_CmdFunc_Play, SA_CMDCLS_MUSIC, 1, AT_MUSIC_PERM},
  {(UINT8*)"+MPAUSE", AT_MUSIC_CmdFunc_Pause, SA_CMDCLS_MUSIC, 1, AT_MUSIC_PERM},
  {(UINT8*)"+MMODE", AT_MUSIC_CmdFunc_ModeSwitch, SA_CMDCLS_MUSIC, 1, AT_MUSIC_PERM},
  {(UINT8*)"+MSTATE", AT_MUSIC_CmdFunc_State, SA_CMDCLS_MUSIC, 1, AT_MUSIC_PERM},

#if defined(APP_SUPPORT_UART_PLAY) && (APP_SUPPORT_UART_PLAY == 1)
  {(UINT8*)"+MUPLAY", AT_MUSIC_UartPlay_CmdFunc_Play, SA_CMDCLS_MUSIC, 1, AT_MUSIC_PERM},
  {(UINT8*)"+MUPAUSE", AT_MUSIC_UartPlay_CmdFunc_Pause, SA_CMDCLS_MUSIC, 1, AT_MUSIC_PERM},
  {(UINT8*)"+MURESUME", AT_MUSIC_UartPlay_CmdFunc_Resume, SA_CMDCLS_MUSIC, 1, AT_MUSIC_PERM},
  {(UINT8*)"+MUSTOP", AT_MUSIC_UartPlay_CmdFunc_Stop, SA_CMDCLS_MUSIC, 1, AT_MUSIC_PERM},
  {(UINT8*)"+MURAWDATA", AT_MUSIC_UartPlay_CmdFunc_RawData, SA_CMDCLS_MUSIC, 1, AT_MUSIC_PERM},
  {(UINT8*)"+MUSETMICGAIN", AT_MUSIC_UartPlay_CmdFunc_SetMicGain, SA_CMDCLS_MUSIC, 1, AT_MUSIC_PERM},
  {(UINT8*)"+MUGETSTATUS", AT_MUSIC_UartPlay_CmdFunc_GetStatus, SA_CMDCLS_MUSIC, 1, AT_MUSIC_PERM},

  {(UINT8*)"+FTCODEC", AT_MUSIC_UartPlay_CmdFunc_FTCodec, SA_CMDCLS_MUSIC, 1, AT_MUSIC_PERM},
  {(UINT8*)"+MSGPLAY", AT_MUSIC_UartPlay_CmdFunc_PlayInterAud, SA_CMDCLS_MUSIC, 1, AT_MUSIC_PERM},
#endif /* APP_SUPPORT_UART_PLAY */
#endif /* __AT_MOD_MUSIC__ */

#if defined(__AT_MOD_COMMON__)
  {(UINT8*)"+CNEXT", AT_COMMON_CmdFunc_Next, SA_CMDCLS_COMMON, 1, AT_COMMON_PERM},
  {(UINT8*)"+CPREV", AT_COMMON_CmdFunc_Prev, SA_CMDCLS_COMMON, 1, AT_COMMON_PERM},
  {(UINT8*)"+CFORE", AT_COMMON_CmdFunc_Fore, SA_CMDCLS_COMMON, 1, AT_COMMON_PERM},
  {(UINT8*)"+CBACK", AT_COMMON_CmdFunc_Back, SA_CMDCLS_COMMON, 1, AT_COMMON_PERM},
  {(UINT8*)"+CVOLADD", AT_COMMON_CmdFunc_VolAdd, SA_CMDCLS_COMMON, 1, AT_COMMON_PERM},
  {(UINT8*)"+CVOLSUB", AT_COMMON_CmdFunc_VolSub, SA_CMDCLS_COMMON, 1, AT_COMMON_PERM},
  {(UINT8*)"+CVOLUME", AT_COMMON_CmdFunc_Volume, SA_CMDCLS_COMMON, 1, AT_COMMON_PERM},
  {(UINT8*)"+CPLAYTONE", AT_COMMON_CmdFunc_PlayTone, SA_CMDCLS_COMMON, 1, AT_COMMON_PERM},
  {(UINT8*)"+CMODE", AT_COMMON_CmdFunc_ModeSwitch, SA_CMDCLS_COMMON, 1, AT_COMMON_PERM},

  {(UINT8*)"+CSLEEP", AT_COMMON_CmdFunc_Sleep, SA_CMDCLS_COMMON, 1, AT_COMMON_PERM},
  {(UINT8*)"+CRESET", AT_COMMON_CmdFunc_Reset, SA_CMDCLS_COMMON, 1, AT_COMMON_PERM},
  {(UINT8*)"+CSHUTDOWN", AT_COMMON_CmdFunc_Shutdown, SA_CMDCLS_COMMON, 1, AT_COMMON_PERM},
  {(UINT8*)"+CRPREG", AT_COMMON_CmdFunc_ReadPeripheralReg, SA_CMDCLS_COMMON, 1, AT_COMMON_PERM},
  {(UINT8*)"+CWPREG", AT_COMMON_CmdFunc_WritePeripheralReg, SA_CMDCLS_COMMON, 1, AT_COMMON_PERM},
  {(UINT8*)"+CVERSION", AT_COMMON_CmdFunc_Version, SA_CMDCLS_COMMON, 1, AT_COMMON_PERM},
#endif

#if defined(__AT_MOD_RECORD__)
  {(UINT8*)"+RSTART", AT_RECORD_CmdFunc_Start, SA_CMDCLS_RECORD, 1, AT_RECORD_PERM},
  {(UINT8*)"+RPAUSE", AT_RECORD_CmdFunc_Pause, SA_CMDCLS_RECORD, 1, AT_RECORD_PERM},

  {(UINT8*)"+RUSTART", AT_RECORD_CmdFunc_UartStart, SA_CMDCLS_RECORD, 1, AT_RECORD_PERM},
  {(UINT8*)"+RUSTOP", AT_RECORD_CmdFunc_UartStop, SA_CMDCLS_RECORD, 1, AT_RECORD_PERM},
#endif

#if defined(__AT_MOD_FM__)
  {(UINT8*)"+FMAUTO", AT_FM_CmdFunc_AutoSearch, SA_CMDCLS_RECORD, 1, AT_FM_PERM},
  {(UINT8*)"+FMMODE", AT_FM_CmdFunc_HoldMode, SA_CMDCLS_RECORD, 1, AT_FM_PERM},
  {(UINT8*)"+FMSTOPSEARCH", AT_FM_CmdFunc_StopSearch, SA_CMDCLS_RECORD, 1, AT_FM_PERM},
  {(UINT8*)"+FMFREQ", AT_FM_CmdFunc_Frequence, SA_CMDCLS_RECORD, 1, AT_FM_PERM},
  {(UINT8*)"+FMSTATE", AT_FM_CmdFunc_GetState, SA_CMDCLS_RECORD, 1, AT_FM_PERM},
#endif

#if defined(__AT_MOD_SPECIAL__)
    {(UINT8 *)"+CAVCP", AT_EMOD_CmdFunc_CAVCP, SA_CMDCLS_SYS, 1, AT_AT_PERM},
    {(UINT8 *)"+CACCP", AT_EMOD_CmdFunc_CACCP, SA_CMDCLS_SYS, 1, AT_AT_PERM},
    {(UINT8 *)"+CAMCP", AT_EMOD_CmdFunc_CAMCP, SA_CMDCLS_SYS, 1, AT_AT_PERM},
    {(UINT8 *)"+CAWTF", AT_EMOD_CmdFunc_CAWTF, SA_CMDCLS_SYS, 1, AT_AT_PERM},
    {(UINT8 *)"+CAIET", AT_EMOD_CmdFunc_CAIET, SA_CMDCLS_SYS, 1, AT_AT_PERM},
#endif
#if (0)

    //Bluetooth
    {(UINT8*)"+BTSET", AT_EMOD_CmdFunc_BTSET, SA_CMDCLS_EX, 1, AT_BTSET_PERM},
    //WIFI
#ifdef __BT_RDABT__
    {(UINT8*)"+BOPEN", AT_BT_CmdFunc_bOpen, SA_CMDCLS_EX, 1, AT_WIFISET_PERM},
    {(UINT8*)"+BCLOSE", AT_BT_CmdFunc_bClose, SA_CMDCLS_EX, 1, AT_WIFISET_PERM},
    {(UINT8*)"+BSET", AT_BT_CmdFunc_bSet, SA_CMDCLS_EX, 1, AT_WIFISET_PERM},
#endif


#if defined(__AT_CONTROL_BT__)
    {(UINT8*)"+BTINQUIRE", AT_EMOD_CmdFunc_BTINQUIRE, SA_CMDCLS_EX, 1, AT_BTINQUIRE_PERM},
    {(UINT8*)"+BTBOND", AT_EMOD_CmdFunc_BTBOND, SA_CMDCLS_EX, 1, AT_BTBIND_PERM},
    {(UINT8*)"+BTACTIVATE", AT_EMOD_CmdFunc_BTACTIVATE, SA_CMDCLS_EX, 1, AT_BTACTIVATE_PERM},
    {(UINT8*)"+BTSPPENABLE", AT_EMOD_CmdFunc_BTSPPENABLE, SA_CMDCLS_EX, 1, AT_BTSPPENABLE_PERM},
#endif
#if defined(__AT_GPS__)
    {(UINT8*)"+GPS", AT_EMOD_CmdFunc_GPS, SA_CMDCLS_EX, 1, AT_GPS_PERM},
    {(UINT8*)"+GPSSLEEP", AT_EMOD_CmdFunc_GPS_Sleep, SA_CMDCLS_EX, 1, AT_GPSSLEEP_PERM},
    {(UINT8*)"+GPSSEND", AT_EMOD_CmdFunc_GPS_Send, SA_CMDCLS_EX, 1, AT_GPSSEND_PERM},
    {(UINT8*)"+GPSI2C", AT_EMOD_CmdFunc_GPS_I2C, SA_CMDCLS_EX, 1, AT_GPSI2C_PERM},
#endif

#endif /* 0 */

    {NULL, NULL, SA_CMDCLS_INVALID_, 1, {0xFFFFFFFF, 0xFFFFFFFF}},
};

