/* 
* Copyright (c) 2006-2016 RDA Microelectronics, Inc.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#ifndef MAP_EXPORT_H
#define MAP_EXPORT_H

/* This file defines the addresses of exported variables.
   It's created by voc_map automatically.*/

#define VPP_SPEECH_DEC_IN_STRUCT                	(0 + RAM_X_BEGIN_ADDR)
#define VPP_SPEECH_ENC_OUT_STRUCT               	(26 + RAM_X_BEGIN_ADDR)
#define VPP_SPEECH_ENC_IN_STRUCT                	(48 + RAM_X_BEGIN_ADDR)
#define VPP_SPEECH_DEC_OUT_STRUCT               	(368 + RAM_X_BEGIN_ADDR)
#define GLOBAL_NOTCH_FILTER_COEF_ADDR           	(7000 + RAM_X_BEGIN_ADDR)
#define VPP_SPEECH_INIT_STRUCT                  	(0 + RAM_Y_BEGIN_ADDR)
#define VPP_SPEECH_AUDIO_CFG_STRUCT             	(56 + RAM_Y_BEGIN_ADDR)
#define SPEEX_NOISE_SUPPRESS_DEFAULT_TX         	(220 + RAM_Y_BEGIN_ADDR)
#define SPEEX_NOISE_SUPPRESS_DEFAULT_RX         	(221 + RAM_Y_BEGIN_ADDR)
#define SPEEX_NOISE_PROB_MIN_TX_RANGE1          	(222 + RAM_Y_BEGIN_ADDR)
#define SPEEX_NOISE_PROB_MIN_TX_RANGE2          	(223 + RAM_Y_BEGIN_ADDR)
#define SPEEX_NOISE_PROB_MIN_TX_RANGE3          	(224 + RAM_Y_BEGIN_ADDR)
#define SPEEX_NOISE_PROB_MIN_TX_RANGE4          	(225 + RAM_Y_BEGIN_ADDR)
#define SPEEX_NOISE_PROB_MIN_RX_RANGE1          	(226 + RAM_Y_BEGIN_ADDR)
#define SPEEX_NOISE_PROB_MIN_RX_RANGE2          	(227 + RAM_Y_BEGIN_ADDR)
#define SPEEX_NOISE_PROB_MIN_RX_RANGE3          	(228 + RAM_Y_BEGIN_ADDR)
#define SPEEX_NOISE_PROB_MIN_RX_RANGE4          	(229 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_MSDF_RELOAD_FLAG                 	(231 + RAM_Y_BEGIN_ADDR)
#define MIC_NONCLIP_ENABLE_FLAG_ADDR            	(236 + RAM_Y_BEGIN_ADDR)
#define RECEIVER_NONCLIP_ENABLE_FLAG_ADDR       	(237 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_NON_CLIP_SMOOTH_THRESHOLD_TX     	(238 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_NON_CLIP_NOISE_THRESHOLD_TX      	(239 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_NON_CLIP_SMOOTH_THRESHOLD_RX     	(240 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_NON_CLIP_NOISE_THRESHOLD_RX      	(241 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_TX_BEFORE_ENC_ADDR               	(244 + RAM_Y_BEGIN_ADDR)
#define NONCLIP_ENABLE_FLAG_ADDR                	(346 + RAM_Y_BEGIN_ADDR)
#define SCALE_MIC_ENABLE_FLAG_ADDR              	(348 + RAM_Y_BEGIN_ADDR)
#define SCALE_RECEIVER_ENABLE_FLAG_ADDR         	(349 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_MIC_SCALE_IN_ADDR                	(350 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_RECEIVER_SCALE_OUT_ADDR          	(351 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_HIGH_PASS_FILTER3_NUM1_ADDR      	(360 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_HIGH_PASS_FILTER3_NUM2_ADDR      	(361 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_HIGH_PASS_FILTER3_DEN1_ADDR      	(362 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_HIGH_PASS_FILTER3_DEN2_ADDR      	(363 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_MIC_DIGITAL_GAIN_ADDR            	(386 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_MIC_DIGITAL_MAXVALUE_ADDR        	(387 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_RECEIVER_DIGITAL_GAIN_ADDR       	(388 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_RECEIVER_DIGITAL_MAXVALUE_ADDR   	(389 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_OUTPUTENERGY_ADDR                	(390 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_INPUTENERGY_ADDR                 	(392 + RAM_Y_BEGIN_ADDR)
#define m_IIRProcPara_ADDR                      	(394 + RAM_Y_BEGIN_ADDR)
#define IIR_ENABLE_FLAG_ADDR                    	(436 + RAM_Y_BEGIN_ADDR)
#ifdef USE_OLD_AEC_NS
#define GLOBAL_AGC_CODE_ADDR                    	(508 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_AGC_CONSTX_ADDR                  	(510 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_MIC_AGC_RAMX_BACKUP_ADDR         	(512 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_RECEIVER_AGC_RAMX_BACKUP_ADDR    	(514 + RAM_Y_BEGIN_ADDR)
#define MIC_AGC_ENABLE_FLAG_ADDR                	(516 + RAM_Y_BEGIN_ADDR)
#define RECEIVER_AGC_ENABLE_FLAG_ADDR           	(517 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_MICAGC_RELOAD                    	(518 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_RECEIVERAGC_RELOAD               	(519 + RAM_Y_BEGIN_ADDR)
#define STRUCT_MicAgcConfig_addr                	(520 + RAM_Y_BEGIN_ADDR)
#define STRUCT_ReceiverAgcConfig_addr           	(524 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_MICFIR_ENABLE_FLAG_ADDR          	(528 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_RECEIVERFIR_ENABLE_FLAG_ADDR     	(529 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_MIC_NOISE_SUPPRESS_SPEAKER_GAIN_ADDR	(552 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_MIC_NOISE_SUPPRESS_LEAK_ESTIMATE_ADDR	(553 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_SPEECH_RAMX_BACKUP_ADDR          	(554 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_SPEECH_CODE_BACKUP_ADDR          	(556 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_AEC_RAMX_BACKUP_ADDR             	(558 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_AEC_CODE_ADDR                    	(560 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_AEC_CONSTX_ADDR                  	(562 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_RX_ADDR                          	(564 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_TX_ADDR                          	(566 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_NOISESUPPRESS_CODE_ADDR          	(568 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_NOISESUPPRESS_CONSTX_ADDR        	(570 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_MIC_NOISESUPPRESS_RAMX_BACKUP_ADDR	(572 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_RECEIVER_NOISESUPPRESS_RAMX_BACKUP_ADDR	(574 + RAM_Y_BEGIN_ADDR)
#define m_AECProcPara_ADDR                      	(576 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_SPEECH_RECORD_FLAG               	(627 + RAM_Y_BEGIN_ADDR)
#define MORPHVOICE_ENABLE_FLAG_ADDR             	(630 + RAM_Y_BEGIN_ADDR)
#define PITCH_SHIFT_ADDR                        	(631 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_BLUETOOTH_RX_ADDR                	(632 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_BLUETOOTH_TX_ADDR                	(634 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_EXTERN_PROCESS_MIC_HANDLE_FLAG   	(8940 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_EXTERN_PROCESS_MIC_ENABLE_FLAG   	(8941 + RAM_Y_BEGIN_ADDR)
#define HIGH_PASS_FILTER_ENABLE_FLAG_ADDR       	(8942 + RAM_Y_BEGIN_ADDR)
#define NOTCH_FILTER_ENABLE_FLAG_ADDR           	(8943 + RAM_Y_BEGIN_ADDR)
#define MIC_NOISE_SUPPRESSER_ENABLE_FLAG_ADDR   	(8944 + RAM_Y_BEGIN_ADDR)
#define RECEIVER_NOISE_SUPPRESSER_ENABLE_FLAG_ADDR	(8945 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_MORPH_RAMX_BACKUP_ADDR           	(8948 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_AEC_SPK_DIGITAL_GAIN_ADDR        	(8954 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_AEC_SPK_DIGITAL_MAXVALUE_ADDR    	(8955 + RAM_Y_BEGIN_ADDR)
#define CVSD_LOWPASS_FILTER_STRUCT              	(8956 + RAM_Y_BEGIN_ADDR)
#define CVSD_LOWPASS_FILTER_ROUND               	(9104 + RAM_Y_BEGIN_ADDR)
#define CVSD_DEC_OUTPUT_ROUND                   	(9106 + RAM_Y_BEGIN_ADDR)
#define CVSD_LOWPASS_DEC_ENC_FLAG               	(9108 + RAM_Y_BEGIN_ADDR)
#define CVSD_enc_delta                          	(9110 + RAM_Y_BEGIN_ADDR)
#define CVSD_dec_delta                          	(9112 + RAM_Y_BEGIN_ADDR)
#define CVSD_delta_min                          	(9114 + RAM_Y_BEGIN_ADDR)
#define CVSD_delta_max                          	(9116 + RAM_Y_BEGIN_ADDR)
#define CVSD_y_min                              	(9118 + RAM_Y_BEGIN_ADDR)
#define CVSD_y_max                              	(9120 + RAM_Y_BEGIN_ADDR)
#define CVSD_enc_xest_l                         	(9122 + RAM_Y_BEGIN_ADDR)
#define CVSD_dec_xest_l                         	(9124 + RAM_Y_BEGIN_ADDR)
#define CVSD_ENC_JUDGE_alpha_buf                	(9126 + RAM_Y_BEGIN_ADDR)
#define CVSD_enc_first_frame_flag               	(9128 + RAM_Y_BEGIN_ADDR)
#define BT_SPEECH_VOC_CVSD_enable               	(9168 + RAM_Y_BEGIN_ADDR)
#define NS_MIC_GAIN_ADDR                        	(9169 + RAM_Y_BEGIN_ADDR)
#else
#define m_AECExtraPara_ADDR                     	(508 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_CVSD_CODE_ADDR                   	(576 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_AGC_CODE_ADDR                    	(578 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_AGC_CONSTX_ADDR                  	(580 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_MIC_AGC_RAMX_BACKUP_ADDR         	(582 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_RECEIVER_AGC_RAMX_BACKUP_ADDR    	(584 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_MICAGC_RELOAD                    	(586 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_RECEIVERAGC_RELOAD               	(587 + RAM_Y_BEGIN_ADDR)
#define STRUCT_MicAgcConfig_addr                	(588 + RAM_Y_BEGIN_ADDR)
#define STRUCT_ReceiverAgcConfig_addr           	(600 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_MICFIR_ENABLE_FLAG_ADDR          	(612 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_RECEIVERFIR_ENABLE_FLAG_ADDR     	(613 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_MIC_NOISE_SUPPRESS_SPEAKER_GAIN_ADDR	(636 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_MIC_NOISE_SUPPRESS_LEAK_ESTIMATE_ADDR	(637 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_SPEECH_RAMX_BACKUP_ADDR          	(638 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_SPEECH_CODE_BACKUP_ADDR          	(640 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_AEC_RAMX_BACKUP_ADDR             	(642 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_AEC_CODE_ADDR                    	(644 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_AEC_CONSTX_ADDR                  	(646 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_RX_ADDR                          	(648 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_TX_ADDR                          	(650 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_NOISESUPPRESS_CODE_ADDR          	(652 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_NOISESUPPRESS_CONSTX_ADDR        	(654 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_MIC_NOISESUPPRESS_RAMX_BACKUP_ADDR	(656 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_RECEIVER_NOISESUPPRESS_RAMX_BACKUP_ADDR	(658 + RAM_Y_BEGIN_ADDR)
#define m_AECProcPara_ADDR                      	(660 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_BLUETOOTH_RX_ADDR                	(712 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_BLUETOOTH_TX_ADDR                	(714 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_EXTERN_PROCESS_MIC_HANDLE_FLAG   	(9020 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_EXTERN_PROCESS_MIC_ENABLE_FLAG   	(9021 + RAM_Y_BEGIN_ADDR)
#define HIGH_PASS_FILTER_ENABLE_FLAG_ADDR       	(9022 + RAM_Y_BEGIN_ADDR)
#define NOTCH_FILTER_ENABLE_FLAG_ADDR           	(9023 + RAM_Y_BEGIN_ADDR)
#define MIC_NOISE_SUPPRESSER_ENABLE_FLAG_ADDR   	(9024 + RAM_Y_BEGIN_ADDR)
#define RECEIVER_NOISE_SUPPRESSER_ENABLE_FLAG_ADDR	(9025 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_MORPH_RAMX_BACKUP_ADDR           	(9028 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_AEC_SPK_DIGITAL_GAIN_ADDR        	(9034 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_AEC_SPK_DIGITAL_MAXVALUE_ADDR    	(9035 + RAM_Y_BEGIN_ADDR)
#define CVSD_LOWPASS_FILTER_STRUCT              	(9036 + RAM_Y_BEGIN_ADDR)
#define CVSD_LOWPASS_FILTER_ROUND               	(9184 + RAM_Y_BEGIN_ADDR)
#define CVSD_DEC_OUTPUT_ROUND                   	(9186 + RAM_Y_BEGIN_ADDR)
#define CVSD_LOWPASS_DEC_ENC_FLAG               	(9188 + RAM_Y_BEGIN_ADDR)
#define CVSD_enc_delta                          	(9190 + RAM_Y_BEGIN_ADDR)
#define CVSD_dec_delta                          	(9192 + RAM_Y_BEGIN_ADDR)
#define CVSD_delta_min                          	(9194 + RAM_Y_BEGIN_ADDR)
#define CVSD_delta_max                          	(9196 + RAM_Y_BEGIN_ADDR)
#define CVSD_y_min                              	(9198 + RAM_Y_BEGIN_ADDR)
#define CVSD_y_max                              	(9200 + RAM_Y_BEGIN_ADDR)
#define CVSD_enc_xest_l                         	(9202 + RAM_Y_BEGIN_ADDR)
#define CVSD_dec_xest_l                         	(9204 + RAM_Y_BEGIN_ADDR)
#define CVSD_ENC_JUDGE_alpha_buf                	(9206 + RAM_Y_BEGIN_ADDR)
#define CVSD_enc_first_frame_flag               	(9208 + RAM_Y_BEGIN_ADDR)
#define BT_SPEECH_VOC_CVSD_enable               	(9248 + RAM_Y_BEGIN_ADDR)
#define NS_MIC_GAIN_ADDR                        	(9249 + RAM_Y_BEGIN_ADDR)

#endif
#endif
